apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-name
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
  encrypted: "true"
  kmsKeyId: "364fca1a-4ed0-456b-b3f1-bcfce02f55cb"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: storage-class-name

---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: test
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
        - mountPath: "/var/www/html"
          name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: mypvc