apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-ingress
  namespace: mongo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "mondb-test.test.medirecords.com"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: mongodb-service
              port:
                number: 27017

