apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-ingress
  namespace: mongo
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: "mondb-test.vpn.medirecords.com"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: mongodb-service
              port:
                number: 27017

