apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix
  labels:
    app: ngnix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - name: ngnix
        image: nginx
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: ngnix-service
spec:
  selector:
    app: ngnix
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80