apiVersion: v1
kind: Service
metadata:
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  name: {{ include "mongo-express.fullname" . }}
  labels:
    {{- include "mongo-express.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mongo-express.selectorLabels" . | nindent 4 }}
